version: "3.9"
services:
  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my_network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
    networks:
      - my_network
    restart: always
    environment:
      PORT: 3000
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      REDIS_HOST: redis_service
      REDIS_PORT: 6379
    
networks:
  my_network:
    driver: bridge