name: "Build Reusable Workflow For Node app"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  build:
    name: Build Node App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/prepare-action

      - name: build
        run:  |
          npm run build

      - name: Cache the app dependencies
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-app