name: SonarQube Security Scan
on: 
  workflow_call:
    secrets:
      TOKEN:
        required: true
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'https://www.zaproxy.org/'