name: "Release Node App"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  release:
    name: release Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/prepare-action
        with:
          node-version: ${{ inputs.node-version }}

      - name: Restore the cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-app

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: vue-build-artifacts
      #     path: |
      #       node_modules/